version: "3"
services:
  kafka:
    image: wurstmeister/kafka:0.10.0.1-2
    networks:
      - streaming-data-internal
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
    depends_on:
      - zookeeper

  hadoop:
    image: sequenceiq/hadoop-docker:2.7.0
    command: "/etc/bootstrap.sh -d"
    networks:
      - streaming-data-internal
    ports:
      - "50070:50070"
      - "50075:50075"
      - "8088:8088"
      - "8042:8042"
      - "9000:9000"
      - "50010:50010"

  hadoop-seed:
    build:
      context: ../hdfs
    networks:
      - streaming-data-internal
    depends_on:
      - hadoop
    restart: on-failure

  zookeeper:
    image: zookeeper:3.3.6
    networks:
      - streaming-data-internal
    ports:
      - "2181:2181"

  zookeeper-seed:
    build:
      context: ../zookeeper
    networks:
      - streaming-data-internal
    depends_on:
      - zookeeper


  station-san-francisco-producer:
    build:
      context: ../CitibikeApiProducer
      dockerfile: Dockerfile-station-san-francisco-e2e
    depends_on:
      - kafka
      - zookeeper-seed
    networks:
      - streaming-data-internal

  station-consumer:
    build:
      context: ../StationConsumer
    depends_on:
      - zookeeper-seed
      - kafka
      - station-san-francisco-producer
    volumes:
      - ~/.ivy2:/root/.ivy2:rw
    command: ["./wait-for.sh", "zookeeper:2181", "-t", "30"]
    networks:
      - streaming-data-internal
    restart: on-failure


  webserver:
    container_name: "webserver"
    build:
      context: ../docker/airflow/
    restart: always
    environment:
      - EXECUTOR=Sequential
      - AIRFLOW__CORE__FERNET_KEY=1uU2E6EgdCmdHKebTZjQYvhCzqv8Q597vULxXJy-blE=
      - FERNET_KEY=1uU2E6EgdCmdHKebTZjQYvhCzqv8Q597vULxXJy-blE=
    volumes:
        - ${PWD}/airflow/dags:/usr/local/airflow/dags
    ports:
      - "8090:8080"
      - "588:587"
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - config.env




networks:
  streaming-data-internal:
